### ISSUE TITLE
Problem with modding 

### ISSUE THREAD

**Issue by xander5002** [Carsmaniac/paintjob-packer#13]
I was working with paintjob packer for some time now and everything went fine before the update but after the update I wanted to make another mod but when I openend the mod in paint.net I only saw a blank square as my canvas and I didn’t see the truck design that you would normally see.

**Comment by Carsmaniac** [comment]
I've left a detailed answer with screenshots [on the SCS Forums](https://forum.scssoft.com/viewtopic.php?p=1661732#p1661732), if you need any more help feel free to reply either here or there :)

**Comment by xander5002** [comment]
I previously had a problem with paintjob packer but now I have stumbled on another problem because, I followed your advise step by step but when I want to make a skin for a trailer it doesn't work because when I tried it out I did everything the same as when I'm skinning a truck but now when I make both sides of the trailer skin are on just one side
