### ISSUE TITLE
Problem to start PJP v1.9+

### ISSUE THREAD

**Issue by claudioivp** [Carsmaniac/paintjob-packer#15]
Paint Job Packer can't find its library files
Make sure that the "library" folder is in the same directory as packer.py, and it contains all of its files
Press enter to quit
![Capturar](https://user-images.githubusercontent.com/2648554/158108048-811f9b5f-80da-4b18-b303-788d4a3f5603.PNG)

At version 1.8 starts normally

**Comment by stophman1** [comment]
The author didn't make the error catcher very specific, but I assume you are probably also having problems with the analytics scripts. The easiest solution is to comment out lines 25 `import library.analytics`, 1331 ` multi_thread_analytics = threading.Thread(...)`, and 1332 `multi_thread_analytics.start()`.

**Comment by Carsmaniac** [comment]
@stophman1 Thanks for your help. I actually fixed this bug in v1.9.2 as far as I can tell, I just forgot about this issue (and all the other issues on GitHub tbh). I'm going to close this one, but if you're still having this problem @claudioivp let me know!
