### ISSUE TITLE
[Feature Request] Metallic Paint Option

### ISSUE THREAD

**Issue by chandujr** [Carsmaniac/paintjob-packer#4]
So far I have really liked this. It does what it says. I have a suggestion to add metallic paint option, like we see in Ets2Studio.

**Comment by Carsmaniac** [comment]
I've considered adding metallic paintjobs, as well as paintjobs with changeable colours, but I ultimately decided against it as they're too complicated.

Making a mod in Paintjob Packer is pretty straightforward, and once the mod is generated all you ever have to change are the images and mod description, however metallic paintjobs require you to edit .def files after the fact (and understand the SCS colour space while doing it). I'll be limiting Paintjob Packer to simple airbrush paintjobs for now, for simplicity's sake/

Thanks for the feature request, and sorry it took so long for me to reply!

**Comment by chandujr** [comment]
No problem. This is still a great tool.
