### ISSUE TITLE
Warn about illegal characters (e.g. period at the end) in name

### ISSUE THREAD

**Issue by azumukupoe** [Carsmaniac/paintjob-packer#5]

**Comment by Carsmaniac** [comment]
The program already shows a warning if there is an illegal character, however at the moment I only check for characters that break the .sii file format: `/ \ "`

I totally forgot about characters that mess up file paths, including periods. I'll be adding warnings for the following characters in the next update: `: * ? < > | .`

Thank you very much for letting me know about the problem, and taking the time to create an issue! :)
