### ISSUE TITLE
"Something went very wrong"

### ISSUE THREAD

**Issue by LilCuteli** [Carsmaniac/paintjob-packer#9]
When I finalize the creation of the mod in the app, this error log appears:

PermissionError: [Errno 13] Permission denied: 'C:/Users/Notebook/Desktop/Paintjob Packer Output/bbbba/Mod_Manager_Image.jpg'

Traceback:
  File "tkinter\__init__.py", line 1892, in __call__

  File "packer.py", line 413, in <lambda>

  File "packer.py", line 828, in check_if_folder_clear

  File "packer.py", line 926, in make_paintjob

  File "library\paintjob.py", line 134, in copy_mod_manager_image
    shutil.copyfile("library/placeholder files/mod_manager_image.jpg", output_path + "/Mod_Manager_Image.jpg")

  File "shutil.py", line 264, in copyfile

**Comment by Carsmaniac** [comment]
Thanks for reporting the issue, may I ask why you closed it? I thought I addressed this crash in v1.8, were you running an older version, and updating fixed it, by any chance? Thanks!

**Comment by LilCuteli** [comment]
I'm very very sorry, but in the heat of the moment I addressed the issue even tho it was the simplest thing to ever exist, the antivirus was blocking it for some reason.
I solved by just disabling the antivirus from checking that app.
